name: Publish poi container to Azure Container Registry
on:
  push:
    paths:
      - "src/poi/**"
jobs:
  acr_build:
    runs-on: ubuntu-latest
    steps:
      - name: ACR build
        id: acr
        uses: Azure/acr-build@master
        with:
          service_principal: ${{ secrets.service_principal }}
          service_principal_password: ${{ secrets.service_principal_password }}
          tenant: ${{ secrets.tenant }}
          registry: ${{ secrets.registry }}
          repository: ${{ secrets.repository }}
          image: poi
          folder: src/poi
          dockerfile: ../../dockerfiles/Dockerfile_3
